vich_uploader:
  db_driver: orm

    mappings:
       categories:
           uri_prefix: /images/categories
           upload_destination: '%kernel.project_dir%/public/images/categories'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       devis:
           uri_prefix: /images/devis
           upload_destination: '%kernel.project_dir%/public/images/devis'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       avis:
           uri_prefix: /images/avis
           upload_destination: "%kernel.project_dir%/public/images/avis"
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

  metadata:
    type: attribute
